fasticionarios: fasticionarios.c
	gcc fasticionarios.c -O3 -g0 -o fasticionarios
fasdebug: fasticionarios.c
	gcc fasticionarios.c -O3 -g0 -o fasdebug -D DEBUG
fastest: fasticionarios.c
	gcc fasticionarios.c -o fastest -O3 -D TEST_BINARY -D DEBUG
clean:
	rm -v fastest fasdebug fasticionarios

